### PR TITLE
Switch to `oneunit` (and other smaller changes)

### LINKED ISSUE #56: scalar multiplication fails on RGB24
Hi folks I am working on  `ColorVectorSpace` Version 0.1.8. If I try to evaluate `RGB24(1,0,0)*0.5` I get 

```
ERROR: too many parameters for type RGB24
 in *(::Float64, ::ColorTypes.RGB24) at ColorVectorSpace/src/ColorVectorSpace.jl:114
 in *(::ColorTypes.RGB24, ::Float64) at ColorVectorSpace/src/ColorVectorSpace.jl:134
```

There seems to be some underlying problem with `RBG24` since the same happens for vector addition.

### PR DESCRIPTION
**Pull request by timholy**
Base julia has distinguished `one` and `oneunit`, and we should do so, too. This is sure to cause quite a few deprecation warnings in dependent packages (e.g., Images).

This also adds support for `middle` and fixes #56 (in separate commits).

### CODE REVIEW

File: src/ColorVectorSpace.jl [hunk 1]
```diff
@@ -164,13 +171,15 @@ abs2(c::TransparentRGB) = (ret = abs2(color(c)); ret + convert(typeof(ret), alph
 norm(c::AbstractRGB) = sqrt(abs2(c))
 norm(c::TransparentRGB) = sqrt(abs2(c))
 
-one{C<:AbstractRGB}(::Type{C})     = C(1,1,1)
-one{C<:TransparentRGB}(::Type{C})  = C(1,1,1,1)
+oneunit{C<:AbstractRGB}(::Type{C})     = C(1,1,1)
```
Comment (ararslan) [inline src/ColorVectorSpace.jl]: If you use `where`, you'll avoid deprecation warnings on 0.7.

File: src/ColorVectorSpace.jl [hunk 2]
```diff
@@ -354,4 +347,20 @@ typemax{T<:ColorTypes.AbstractGray}(::Type{T}) = T(typemax(eltype(T)))
...
+function Base.one(::Type{C}) where {C<:Union{TransparentGray,AbstractRGB,TransparentRGB}}
+    Base.depwarn("one($C) will soon switch to returning 1; you might need to switch to `oneunit`", :one)
+    C(_onetuple(C)...)
+end
+_onetuple(::Type{C}) where {C<:Colorant{T,N}} where {T,N} = ntuple(d->1, Val(N))
+
+for f in (:min, :max)
+    @eval begin
+        @deprecate($f{T<:Gray}(x::Number, y::AbstractArray{T}),
+                   @compat $f.(x, y))
```
Comment (ararslan) [inline src/ColorVectorSpace.jl]: Since the package no longer supports 0.4, you can drop the `@compat` for dot broadcast.

File: src/ColorVectorSpace.jl (hunk 1 above)
Comment (timholy) [reply src/ColorVectorSpace.jl]: I want to save some work so that femocleaner feels valued. Even bots have feelings.
