### PR TITLE
Redesign color arithmetic

### LINKED ISSUE #126: Important decisions with respect to color math (please comment)
## RGB multiplication and implications for `var` (#119, #125)

Currently multiplication of two RGBs is undefined, but sometimes this causes problems (#119, "tinting" as in https://discourse.julialang.org/t/loaderror-dimensionmismatch/35507?u=tim.holy). In #119, we hit on the possibility of defining `⋅` (`\cdot`) as the "dot product" (with channels viewed as a vector), `*` operating channelwise, and `⊗` (`\otimes`) some day being the outer product (though we currently lack a type to express this result). I'll modify this proposal below, but for now let's run with it and explore the implications. An important route lies through `abs2`...

Currently, `abs2(c)` returns a scalar, which in this proposed framework would be equivalent to defining `abs2(c) = c⋅c`. This is similar to how `abs2` behaves with respect to the real and imaginary components of a complex number. This results in the following:
```julia
julia> using ColorVectorSpace, Statistics

julia> r = rand(RGB{Float32}, 2)
2-element Array{RGB{Float32},1} with eltype RGB{Float32}:
 RGB{Float32}(0.6334499f0,0.34752238f0,0.17738128f0)
 RGB{Float32}(0.35009634f0,0.38727677f0,0.6068548f0)

julia> var(r)
0.13315858f0
```
However, if you load Images it changes the behavior of `var` to be channelwise, because Images specializes `var` for arrays of Colorants :frowning_face: . Rather than overloading `var` for certain element types, we could let `*` be channelwise multiplication and define `abs2(c) = c*c`, and it should even make it robust with respect to the `dims` keyword argument (#125, CC @wizofe).

However, since this package is called Color**VectorSpace** it's also worth noting this comparison:
```julia
julia> using Statistics, StaticArrays

julia> A = rand(3, 5)
3×5 Array{Float64,2}:
 0.901707   0.763397  0.0841844  0.164515  0.542334
 0.247929   0.690001  0.492793   0.275766  0.175159
 0.0860073  0.120248  0.0454239  0.403493  0.529168

julia> var(A; dims=2)
3×1 Array{Float64,2}:
 0.129401636194079  
 0.04475575432189567
 0.04655327916103   

julia> a = reinterpret(SVector{3,Float64}, A)
1×5 reinterpret(SArray{Tuple{3},Float64,1,3}, ::Array{Float64,2}):
 [0.901707, 0.247929, 0.0860073]  …  [0.542334, 0.175159, 0.529168]

julia> var(a; dims=2)
ERROR: MethodError: no method matching abs2(::SArray{Tuple{3},Float64,1,3})
Closest candidates are:
  abs2(::Missing) at missing.jl:100
  abs2(::Bool) at bool.jl:84
  abs2(::Real) at number.jl:157
  ...
Stacktrace:
 [1] (::Statistics.var"#12#13")(::SArray{Tuple{3},Float64,1,3}) at /home/tim/src/julia-1/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:300
...
```
so this is an issue that doesn't have an agreed-upon resolution elsewhere in the ecosystem. We might actually want to be able to pass an operator, and the thinking above inspires me to propose `var(⋅, a)`, `var(*, a)`, and `var(⊗, a)`. 

**However**, this conflicts with the very clear decision that `u*v` for two vectors `u` and `v` is deliberately undefined, and specifically does *not* mean elementwise multiplication (that's what broadcasting is for). Unfortunately, it's not possible to pass broadcasted-`*` (`.*`) as an argument to a function. Consequently we might consider choosing an operator to be a synonym for elementwise multiplication, and leaving `*` undefined for RGB. Options include `∗` (`\ast`), `•` (`\bullet`), and `⊙` (`\odot`). I worry that `\ast` looks too similar to `*` and would be confused for it; if we go this way I think my preference is for `\odot` but curious to see what others think.

By this token `abs2` should be undefined for colors, `var(a)` should throw an error for color arrays, but `var(⊙, a)` should do what users want.

Because of the analogy with arrays-of-vectors I'll open a similar issue in Statistics.jl and see what folks outside of the JuliaImages world think. (Update: https://github.com/JuliaLang/Statistics.jl/issues/29)

## Interaction between color math and conversions

Another factor that would argue in favor of changing the behavior of `abs2` is the following set of logical-sounding conclusions:
- if `x` is a real number, then `Gray(x)` is basically the same thing (other than being a display hint)
- `RGB(Gray(x))` should return `RGB(x, x, x)`, so by the same token `RGB(x, x, x)` is essentially equivalent to `x`

Our current scheme has a big gotcha:
```julia
julia> x = 0.5
0.5

julia> abs2(x)
0.25

julia> abs2(RGB(x, x, x))
0.75
```
so we're in a situation where `a` and `b` can be equivalent but `abs2(a)` is very different from `abs2(b)`. If we changed `abs2` to behave channelwise, we'd restore consistency. An error would also fix it; we don't object to `-1 == -1+0im` but having `sqrt` return an error for just one of them.

## Result types from arithmetic (#38)

I originally designed the rules to be inspired to unitful arithmetic. However, most others who have commented seem to expect that colors will be "poisoning" in much the same way that `NaN` is poisoning in arithmetic. (https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/38#issuecomment-490780645 as well as the OP in #38).

Given that we support `Gray(0.1)^2` and there is no type encoding `Gray^2`, I now think the poisoning metaphor is overall the better choice. 

I suspect there is one interesting exception to the poisoning rule, however, which comes from linear algebra:
```julia
julia> v = SVector((0.2, 0.1, 0.8))
3-element SArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 0.2
 0.1
 0.8

julia> u = SVector((0.1, 0.2, 0.8))
3-element SArray{Tuple{3},Float64,1,3} with indices SOneTo(3):
 0.1
 0.2
 0.8

julia> u \ v
0.9855072463768115
```
Note the returned value is a scalar, not an `SVector{3}`. (The value minimizes `norm(α*u - v)` for real-valued `α`.) Should we define `\` for `Gray` and `RGB`? `/` cannot be defined for `RGB` (EDIT: in the denominator), but it can for `Gray`; should `Gray(0.2) / Gray(0.1)` likewise be "colorless"? That is a little bit more like the unitful design. Is that a good thing, or would that be annoying?

### PR DESCRIPTION
**Pull request by timholy**
This notably defines 3 multiplication operators for RGB colors. It also un-defines `abs2`, because how that should work is a bit ambiguous. Finally, it defines a new `varmult` function, which allows one to compute variance using a specific multiplication operator.

Fixes #126. Requires the following:

- [x] https://github.com/JuliaMath/FixedPointNumbers.jl/pull/177
- [x] https://github.com/JuliaMath/FixedPointNumbers.jl/pull/183
- [ ] https://github.com/JuliaGraphics/ColorTypes.jl/pull/177
- [ ] https://github.com/JuliaGraphics/ColorTypes.jl/pull/186

### CODE REVIEW

File: src/ColorVectorSpace.jl [hunk 1]
```diff
@@ -311,38 +311,115 @@ typemax(::Type{T}) where {T<:ColorTypes.AbstractGray} = T(typemax(eltype(T)))
...
+    rr::T
+    gr::T
+    br::T
+    rg::T
+    gg::T
+    bg::T
+    rb::T
+    gb::T
+    bb::T
+end
```
Comment (kimikage) [inline src/ColorVectorSpace.jl:343]: TBH, I'm not sure how useful the tensor product for colors is...:sweat_smile:

If we introduce new types for the tensor product, I think it's better to make them parametric. Even if they are non-parametric, they should have a parametric supertype.

The reason is that we may also need the tensor product types for color types other than `RGB` (e.g. `ARGB`, `RGBA`, `AGray` and `GrayA`) for consistency rather than practicality. Probably Colors.jl will not support tensor products unless TensorCore is in the `Base` or stdlib. In that case, `XYZ` and `LMS` may need to be extended within ColorVectorSpace.

Also, If we introduce new types, I think it's better to do lazy evaluation. On modern CPUs, the bottleneck is often memory access rather than multiplication.

Creating such a gadget only for color types is an over-investment, but I think doing it in TensorCore.jl isn't too bad.

File: src/ColorVectorSpace.jl [hunk 2]
```diff
@@ -245,42 +261,35 @@ min(a::AbstractGray, b::AbstractGray) = min(promote(a,b)...)
...
-hypot(x::Gray, y::Gray) = hypot(convert(Real, x), convert(Real, y))
-norm(c::TransparentGray) = sqrt(abs2(c))
-
-(<)(g1::AbstractGray, g2::AbstractGray) = gray(g1) < gray(g2)
-(<)(c::AbstractGray, r::Real) = gray(c) < r
-(<)(r::Real, c::AbstractGray) = r < gray(c)
+atan(x::AbstractGray, y::AbstractGray)  = atan(gray(x), gray(y))
+hypot(x::AbstractGray, y::AbstractGray) = hypot(gray(x), gray(y))
+
+if !hasmethod(<, Tuple{AbstractGray,AbstractGray})  # this was moved to ColorTypes 0.11
```
Comment (kimikage) [inline src/ColorVectorSpace.jl:267]: Should we continue to support the old (current) FixedPointNumbers and ColorTypes?
This version should be a "new generation", so I think it's better to break the dependency, even if they are technically compatible.

File: src/ColorVectorSpace.jl (hunk 1 above)
Comment (timholy) [reply src/ColorVectorSpace.jl:343]: > TBH, I'm not sure how useful the tensor product for colors is...sweat_smile

Weren't you asking to make sure we consider the covariance? https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/126#issuecomment-599224928. The tensor product is the natural way to get the covariance---really, there shouldn't be "variance" and "covariance," there is just variance with different multiplication operators.

>  I think it's better to do lazy evaluation

Lazy works great if you're multiplying one RGB by another, but you need something to accumulate the (co)variance into. Typically, after combining the colors of 3 pixels you'll be at a rank-3 matrix, at which point you're better off using "dense" arithmetic.

File: src/ColorVectorSpace.jl (hunk 2 above)
Comment (timholy) [reply src/ColorVectorSpace.jl:267]: That would be fine. This is easier for me locally because I switch between `dev`ved and `free`d versions of packages, but we could hardwire this in the final version.

File: src/ColorVectorSpace.jl (hunk 1 above)
Comment (kimikage) [reply src/ColorVectorSpace.jl:343]: In the first place, is the tensor included in the target of ColorVectorSpace?
I think we should create a new package ColorTensorSpace.jl.:smile: Within the new package, we can feel more free to depend on the existing packages for tensors.

What we should do now is to clarify that multiple multiplication definitions can coexist, and I don't think we need to hurry to implement the tensor product. At least this PR can be split into more atomic changes.

Comment (timholy) [reply src/ColorVectorSpace.jl:343]: I agree that the tensor product is likely to see less use. If it seems premature to implement it in this PR, sure, I can split it out.

Comment (kimikage) [reply src/ColorVectorSpace.jl:343]: I think the current implementation will help we understand the behavior. So, if we consider this to be an experimental feature (even if it seems premature), it may be good to leave the code for the time being. On the other hand, if we need more discussion, I think the separate PR is helpful.

File: README.md [hunk 3]
```diff
@@ -27,16 +36,72 @@ represents the "RGB vector space" version.
...
+
+Note that `c1⋅c2 = (c1.r*c2.r + c1.g*c2.g + c1.b*c2.b)/3`, where the division by 3 ensures the equivalence of `x`, `Gray(x)`, and `RGB(x, x, x)` for scalar `x` as described above for `norm`.
+
+It is not obvious that one of these should be the default notion of multiplication, so the ordinary multiplication operation `*` is undefined for RGB colors.
+(It is defined for grayscale.)
+
+### Variance
+
+The variance `v = E((c - μ)^2)` (or its bias-corrected version) involves a multiplication,
+and consistent with the above you must specify which sense of multiplication you wish to use:
```
[the remark this answers is not in the document]
Comment (timholy) [reply README.md:88]: I'm not sure I know anymore how it works in other languages :smile:. In Matlab, I guess `var(img)` would include the variance over color channels and `var(img, [1, 2])` would compute variance within color channels? Is the former even useful?

[the remark this answers is not in the document]
Comment (johnnychen94) [reply README.md:88]: It's just for clarification purposes only, because these are not available in other languages. I think it's more common to use the channelwise version `[var(img[:, :, 1]), var(img[:, :, 2]), var(img[:, :, 3])]` in practice, which is equivalent to `varmult(⊙, img)`.

File: src/ColorVectorSpace.jl [hunk 4]
```diff
@@ -24,28 +21,75 @@ import Base:      conj, sin, cos, tan, sinh, cosh, tanh,
...
+arith_colorant_type(::Type{Gray24}) = Gray
+arith_colorant_type(::Type{AGray32}) = AGray
+arith_colorant_type(::Type{RGB24}) = RGB
+arith_colorant_type(::Type{ARGB32}) = ARGB
+
+# Useful for leveraging iterator algorithms
+channels(c::AbstractGray)    = (gray(c),)
+channels(c::TransparentGray) = (gray(c), alpha(c))
+channels(c::AbstractRGB)     = (red(c), green(c), blue(c))
+channels(c::TransparentRGB)  = (red(c), green(c), blue(c), alpha(c))
```
Comment (kimikage) [inline src/ColorVectorSpace.jl:80]: I think it's better to generalize these methods in ColorTypes as mentioned in https://github.com/JuliaGraphics/ColorTypes.jl/pull/184#issuecomment-644138321).

However, I think there is a need for more discussion as to whether `channels` should return an iterator or a tuple.
What about a constructor-style `Tuple` conversion method to "buy time" for the debate? It is obvious that `Tuple()` returns a tuple. On the other hand, I don't think it's good to overload `convert` for color --> tuple conversions, since it can be called implicitly.

Another trivial concern is that ColorTypes uses the term "component" (e.g. `comp1`) rather than "channel". I think the "channel" is appropriate for arrays of colors (i.e. images).

File: README.md [hunk 5]
```diff
@@ -27,16 +36,72 @@ represents the "RGB vector space" version.
...
+RGB{Float64}(0.1,0.09,0.08000000000000002)
+
+julia> c1⊗c2     # or tensor(c1, c2)
+RGBRGB{Float64}(
+ 0.1   0.06  0.04000000000000001
+ 0.15  0.09  0.06
+ 0.2   0.12  0.08000000000000002)
+```
+
+Note that `c1⋅c2 = (c1.r*c2.r + c1.g*c2.g + c1.b*c2.b)/3`, where the division by 3 ensures the equivalence of `x`, `Gray(x)`, and `RGB(x, x, x)` for scalar `x` as described above for `norm`.
```
[the remark this answers is not in the document]
Comment (kimikage) [reply README.md:80]: I don't really like this definition. I don't think `⋅` needs to return the "consistent" values with `norm`, from a point of view in programming, not math. Giving different definitions different names (symbols) is exactly what this PR is trying to do.

I also don't really like the definition of `norm`. As you know, the definition of  norm affects the definition of unit vector.
It's a bit strange to equate `Gray(x)` with `RGB(x, x, x)`. More obvious inconsistencies can be found in `TransparentColor`.
```julia
julia> norm(Gray(0.5)) == norm(AGray(0.5))
false
```
We apply the promotion rules(implicit type conversions) on the addition, so it doesn't "seem" to satisfy the triangle inequality. (Of course, it is satisfied in the post-promotion vector space.)

[the remark this answers is not in the document]
Comment (timholy) [reply README.md:81]: We should probably get rid of `norm(::TransparentColor)`.

If you're concerned about the interpretation of `dot`/`⋅` as the Euclidean dot product of a literal vector `[r,g,b]`, then we should change the name/symbol of the operator, not this definition. I am planning on enforcing strict equivalence throughout, it is vital and one of the only guiding principles available.

However, personally I don't think it's an issue. For example we could define
```julia
echannels(g::Gray) = (gray(g),)
echannels(c::RGB) = (red(c)/SQRT3, green(c)/SQRT3, blue(c)/SQRT3)
```
and then no one would argue with the thought that this definition is equivalent to the Euclidean dot product of `echannels(c1) ⋅ echannels(c2)`. In other words, this is just a decision about how you embed these otherwise-opaque objects into a vector space.

File: README.md [hunk 6]
```diff
@@ -27,16 +36,72 @@ represents the "RGB vector space" version.
...
+
+It is not obvious that one of these should be the default notion of multiplication, so the ordinary multiplication operation `*` is undefined for RGB colors.
+(It is defined for grayscale.)
```
[the remark this answers is not in the document]
Comment (timholy) [reply README.md]: Already done in https://github.com/JuliaGraphics/ColorTypes.jl/pull/186/files

File: src/ColorVectorSpace.jl (hunk 4 above)
Comment (timholy) [reply src/ColorVectorSpace.jl:80]: I am not sure anymore that I want to export it. It's just a private method this way.

Comment (kimikage) [reply src/ColorVectorSpace.jl:80]: If we introduce the concept of `echannels` different from `channels`, at least they should be documented. So I think they will be "semi-public", whether or not we export them.

Comment (timholy) [reply src/ColorVectorSpace.jl:80]: I don't think we should have both.

File: src/ColorVectorSpace.jl (hunk 1 above)
Comment (kimikage) [reply src/ColorVectorSpace.jl:343]: cf. https://discourse.julialang.org/t/ann-tensoralgebra-jl-taking-covariance-seriously/43587

Comment (timholy) [reply src/ColorVectorSpace.jl:343]: Once we start auto-differentiating with respect to RGB values, that could indeed be useful.

**Comment by timholy** [comment]
I've made this work with current releases; except for the `hasmethod` and related calls, test coverage is now essentially 100%. (On `master` it's 79%.)

I am leaning towards calling this 0.9, rather than 1.0, and see how things work for a few months.

**Comment by timholy** [comment]
That was a long delay! Good to have this finally done.

File: src/ColorVectorSpace.jl [hunk 7]
```diff
@@ -119,6 +96,47 @@ parametric(::Type{RGB24}, ::Type{N0f8}) = RGB24
...
+
+
+## Rounding & mod
+for f in (:trunc, :floor, :round, :ceil, :eps, :bswap)
+    @eval $f(g::Gray{T}) where {T} = Gray{T}($f(gray(g)))
+end
+eps(::Type{Gray{T}}) where {T} = Gray(eps(T))
+
+for f in (:trunc, :floor, :round, :ceil)
+    @eval $f(::Type{T}, g::Gray) where {T<:Integer} = Gray{T}($f(T, gray(g)))
```
Comment (johnnychen94) [inline src/ColorVectorSpace.jl:129]: This seems to be an over-loose type annotation to me, since we don't really have `Gray{<:Integer}` types except for `Bool`.

https://github.com/JuliaGraphics/ColorTypes.jl/blob/0003cf95fc1ed348490d2a467ee95afea55ee9e0/src/types.jl#L344-L346

Making it 

```julia
$f(::Type{T}, g::Gray) where {T<:Integer} = $f(T, gray(g)))
```

is more reasonable if we consider that `T` specifies the output type for such usages.

cref: https://github.com/JuliaGraphics/ColorTypes.jl/issues/123#issuecomment-1272570990

cc: @myrddin89
